### ISSUE TITLE
problem to use this extension in oommf 2.1a

### ISSUE THREAD

**Issue by MKe2013** [oommf-extensions/anv-spintevolve-3d#1]
Hi,

I have tried to use your package, but I obtain an error: " Error thrown from inside "Oxs_Run" --- Oxs_Ext error inside Run() function Oxs_TimeDruiver --- Oxs_ext ERROR in object Anv_SpintEvolve_3d:: Programming error: Implementation of Oxs_TimeEvolver::Step(const Oxs_timeDrive*, Oxs_ConstKey<Oxs_SimState>, Oxs_DriverStepInfo,Oxs_Key<Oxs_SimState>&) not provided.

I am using oommf 2.1a. I have considered the following implementation:

Specify Anv_SpinTEvolve_3d {
  do_precess 1
  gamma_LL 2.21e5
  method rk4
  alpha 0.01
  beta 0.04

  u {Oxs_ScriptVectorField {
               atlas :disk
               script Current_u
               script_args rawpt
	       norm  1
              
            }}
	
}

Specify Oxs_TimeDriver [subst {
 basename J=0.85e12
 evolver Anv_SpinTEvolve_3d
 stopping_dm_dt 0.001
 mesh :mesh
 m0 :file1
 Ms { Oxs_VecMagScalarField {
   field :file1
}}
}]

Destination savefile mmArchive

Schedule Oxs_TimeDriver::Magnetization savefileStep 100
Schedule DataTable arx savefile 100

What could this error be caused by?

thanks

**Comment by lang-m** [comment]
Hi @MKe2013, I would guess that this error is related to some change inside OOMMF in the 2.1 release. Could you try to use OOMMF 2.0b0?

**Comment by MKe2013** [comment]
Hi, I have tried to compile with oommf 2.0b0. But I get the following error:

tclsh oommf.tcl pimake

/home/Mike/oommf/app/oxs/local/spintevolve_3d.cc: In member function ‘virtual OC_BOOL Anv_SpinTEvolve_3d::Step(const Oxs_TimeDriver*, Oxs_ConstKey<Oxs_SimState>, const Oxs_DriverStepInfo&, Oxs_Key<Oxs_SimState>&)’:
/home/Mike/oommf/app/oxs/local/spintevolve_3d.cc:1842:20: error: ‘const struct Oxs_DriverStepInfo’ has no member named ‘GetCurrentAttemptCount’; did you mean ‘current_attempt_count’?
 1842 |       && step_info.GetCurrentAttemptCount()==0)) {
      |                    ^~~~~~~~~~~~~~~~~~~~~~
      |                    current_attempt_count
<3859> pimake 2.0b0  panic:
child process exited abnormally
1 Error(s) detected

**Comment by lang-m** [comment]
The error is caused by attempts to make the code work with 2.1, sorry I for got about it. 
Please use the version from this release: https://github.com/oommf-extensions/anv-spintevolve-3d/releases/tag/v1.0, which should be compatible with OOMMF 2.0b0.

**Comment by MKe2013** [comment]
Thanks, I was able to compile it. But, When I execute the simulations I obtain the following error: " Error thrown from inside "Oxs_Run" --- Oxs_Ext error inside Run() function of driver Oxs_TimeDriver: --- Oxs_Ext ERROR in object Oxs_UniformExchange:: Programming error: Oxs_UniformExchange max spin angle set to two different values ; orig val = 8.3203906974122877, new val = 8.3203831299501658".

**Comment by MKe2013** [comment]
Changing the method to rkf54s solved it.

**Comment by lang-m** [comment]
@MKe2013 I have fixed the bug, the current main should now be compatible with OOMMF 2.1 (probably only rkf45s). If you are still working on this and want to try out the new version I'd be interested to hear if it is now working fine.
